apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: calico-node
  namespace: kube-system
spec:
  template:
    spec:
      containers:
      - name: calico-node
        resources:
          requests:
            cpu: 40m
            memory: 25Mi
          limits:
            cpu: 250m
            memory: 128Mi

